/**
 * Stable error codes for RFC 7807 Problem Details
 * Required by North Star for consistent error handling
 */

export enum ErrorCode {
  // Reference handling errors
  REF_FETCH_FAILED = 'REF_FETCH_FAILED',
  REF_INVALID_URL = 'REF_INVALID_URL',
  REF_TIMEOUT = 'REF_TIMEOUT',
  
  // Model and API errors
  MODEL_RATE_LIMIT = 'MODEL_RATE_LIMIT',
  MODEL_UNAVAILABLE = 'MODEL_UNAVAILABLE',
  MODEL_INVALID_RESPONSE = 'MODEL_INVALID_RESPONSE',
  
  // Storage errors
  GCS_WRITE_FAILED = 'GCS_WRITE_FAILED',
  GCS_READ_FAILED = 'GCS_READ_FAILED',
  GCS_PERMISSION_DENIED = 'GCS_PERMISSION_DENIED',
  
  // Sheets errors
  SHEETS_WRITE_FAILED = 'SHEETS_WRITE_FAILED',
  SHEETS_READ_FAILED = 'SHEETS_READ_FAILED',
  SHEETS_QUOTA_EXCEEDED = 'SHEETS_QUOTA_EXCEEDED',
  
  // Budget and limits
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  BATCH_SIZE_EXCEEDED = 'BATCH_SIZE_EXCEEDED',
  
  // Validation errors
  INVALID_REQUEST = 'INVALID_REQUEST',
  INVALID_VARIANTS = 'INVALID_VARIANTS',
  INVALID_SCENE_ID = 'INVALID_SCENE_ID',
  
  // Job errors
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_ALREADY_EXISTS = 'JOB_ALREADY_EXISTS',
  JOB_TIMEOUT = 'JOB_TIMEOUT',
  
  // System errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DEPENDENCY_ERROR = 'DEPENDENCY_ERROR'
}

export type ErrorCodeType = keyof typeof ErrorCode;